/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ERRORUNKNOWN } from './eRRORUNKNOWN';


export interface Notification {
    id?: number;
    type?: string;
    always?: boolean;
    web?: boolean;
    mail?: boolean;
    sms?: boolean;
    calendarId?: number;
    attributes?: ERRORUNKNOWN;
}
