/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * This is a permission map that contain two object indexes. It is used to link/unlink objects. Order is important. Example: { deviceId:8, geofenceId: 16 }
 */
export interface Permission {
    /**
     * User Id, can be only first parameter
     */
    userId?: number;
    /**
     * Device Id, can be first parameter or second only in combination with userId
     */
    deviceId?: number;
    /**
     * Group Id, can be first parameter or second only in combination with userId
     */
    groupId?: number;
    /**
     * Geofence Id, can be second parameter only
     */
    geofenceId?: number;
    /**
     * Geofence Id, can be second parameter only and only in combination with userId
     */
    calendarId?: number;
    /**
     * Computed Attribute Id, can be second parameter only
     */
    attributeId?: number;
    /**
     * Driver Id, can be second parameter only
     */
    driverId?: number;
    /**
     * User Id, can be second parameter only and only in combination with userId
     */
    managedUserId?: number;
}
