/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ERRORUNKNOWN } from './eRRORUNKNOWN';


export interface Position {
    id?: number;
    deviceId?: number;
    protocol?: string;
    /**
     * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
     */
    deviceTime?: Date;
    /**
     * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
     */
    fixTime?: Date;
    /**
     * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
     */
    serverTime?: Date;
    outdated?: boolean;
    valid?: boolean;
    latitude?: number;
    longitude?: number;
    altitude?: number;
    /**
     * in knots
     */
    speed?: number;
    course?: number;
    address?: string;
    accuracy?: number;
    network?: string;
    attributes?: ERRORUNKNOWN;
}
