/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ReportTrips {
    deviceId?: number;
    deviceName?: string;
    /**
     * in knots
     */
    maxSpeed?: number;
    /**
     * in knots
     */
    averageSpeed?: number;
    /**
     * in meters
     */
    distance?: number;
    /**
     * in liters
     */
    spentFuel?: number;
    duration?: number;
    /**
     * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
     */
    startTime?: Date;
    startAddress?: string;
    startLat?: number;
    startLon?: number;
    /**
     * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
     */
    endTime?: Date;
    endAddress?: string;
    endLat?: number;
    endLon?: number;
    driverUniqueId?: number;
    driverName?: string;
}
