/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ERRORUNKNOWN } from './eRRORUNKNOWN';


export interface Server {
    id?: number;
    registration?: boolean;
    readonly?: boolean;
    deviceReadonly?: boolean;
    limitCommands?: boolean;
    map?: string;
    bingKey?: string;
    mapUrl?: string;
    poiLayer?: string;
    latitude?: number;
    longitude?: number;
    zoom?: number;
    twelveHourFormat?: boolean;
    version?: string;
    forceSettings?: boolean;
    coordinateFormat?: string;
    attributes?: ERRORUNKNOWN;
}
