/**
 * traccar
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.17
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ERRORUNKNOWN } from './eRRORUNKNOWN';


export interface User {
    id?: number;
    name?: string;
    email?: string;
    readonly?: boolean;
    administrator?: boolean;
    map?: string;
    latitude?: number;
    longitude?: number;
    zoom?: number;
    password?: string;
    twelveHourFormat?: boolean;
    coordinateFormat?: string;
    disabled?: boolean;
    /**
     * in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
     */
    expirationTime?: Date;
    deviceLimit?: number;
    userLimit?: number;
    deviceReadonly?: boolean;
    limitCommands?: boolean;
    poiLayer?: string;
    token?: string;
    attributes?: ERRORUNKNOWN;
}
